### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by Lindsay0214** [LiangYingC/programming-farmer-blog#12]
1. 淺拷貝 shallow
2. 當 Original Object data 與 Cloned Object data ，是兩個完全獨立，每一層的資料地址都不同，相互不影響的深層物件，就為深拷貝(shadow copy)。

**Comment by LiangYingC** [comment]
@Lindsay0214 非常感謝！

我已經在下面兩個 commit 中修復你提及的 typo errors :

fix: shadow copy => shallow copy : 
https://github.com/LiangYingC/programming-farmer-blog/commit/b41f38ff12ce61c3c9fdedc0041cdd09f976224f

fix: replace 深拷貝(shallow copy) with 深拷貝(deep copy) : 
https://github.com/LiangYingC/programming-farmer-blog/commit/4ade0c8ec0ac4e18d832dafcbb128f4b3f347422

並且已經部署到 prod，因此 close 這個 issue。

再次感謝 🙂

Best,
Liang.
