### ISSUE TITLE
Bugs - Event Loop 中 setTimeout 時間值勘誤

### ISSUE THREAD

**Issue by hikrr** [LiangYingC/programming-farmer-blog#13]
# 問題描述 (Bug description)

[link](https://www.programfarmer.com/articles/javaScript/javascript-browser-event-loop) 中提到的 `setTimeout(fn, 1000)` 應該是 1s 不是 0.1s.

文章內容非常的讚，圖文並茂還有動畫 🙏

**Comment by LiangYingC** [comment]
@stagmoose  

感謝你的回報，我已經修復囉，會 closed 這個 issue。

![截圖 2022-07-16 下午10 06 56](https://user-images.githubusercontent.com/56446970/179358289-f992d7b3-fe58-4fb5-a759-df39a704872c.png)

很開心收到你的回饋，希望文章對你有幫助！

Best,
Liang.
