### ISSUE TITLE
Article - suggestion of createElement

### ISSUE THREAD

**Issue by peanshanwu** [LiangYingC/programming-farmer-blog#15]
# 文章網址 (Article links)
https://www.programfarmer.com/articles/2021/react-depth-jsx

# 討論或問題內容（Discussion or error content）
文中其中兩個標題：
1. Using React.createElement to create DOM element
2. Using JSX to create DOM element
<br>

參考 [官方文件](https://react.dev/reference/react/createElement#reference)
<img width="915" alt="截圖 2024-04-12 下午11 44 23" src="https://github.com/LiangYingC/programming-farmer-blog/assets/62551122/954fa9e5-4aa4-4885-9d1a-7da97647a34c">

<br>
可調整為

1. Using React.createElement to create **React element**
2. Using JSX to create **React element**

**Comment by LiangYingC** [comment]
這是很重要的觀念！

當初的我其實完全沒有注意到，已經在這則 PR 中處理，非常感謝 @peanshanwu  : )

https://github.com/LiangYingC/programming-farmer-blog/pull/17
