### ISSUE TITLE
Bugs - 文章中圖片shallow 打成 shadow

### ISSUE THREAD

**Issue by shiqi917** [LiangYingC/programming-farmer-blog#16]
url: https://www.programfarmer.com/articles/2021/javascript-shallow-copy-deep-copy
# 問題描述 (Bug description)
文章中圖片shallow 打成 shadow

**Comment by LiangYingC** [comment]
@zacharyptt 非常感謝，這是重要的細節。

已經在 https://github.com/LiangYingC/programming-farmer-blog/pull/18 這個 PR 修復完畢！
